name: Send Gio Data

on:
  push:
  #workflow_dispatch:

jobs:
  Send:
    name: Send Gio Data
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: sshagent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          echo "The branched that was pushed is $branch"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "maps.media.mit.edu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFqXBJPFe+pH3L57o1ildAxHssG4lpkloTcw3Wbs64c7bL8M6hR0rre4ufpCKboVLn4trJqbKOPWtFgBJHsgqXA=" > ~/.ssh/known_hosts
          touch data.txt
          scp data.txt root@maps.media.mit.edu:/root/map/data/
