name: world map

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: update

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Update database
        env:
          GEO_API_URL: ${{ secrets.GEO_API_URL }}
          LOCAL_DB_URL: ${{ secrets.LOCAL_DB_URL }}
          REMOTE_DB_URL: ${{ secrets.REMOTE_DB_URL }}
          HEADER_KEY: ${{  secrets.HEADER_KEY }}
          HEADER_LOCAL_KEY: ${{ secrets.HEADER_LOCAL_KEY }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        run: |
          mkdir data
          mkdir data/year
          mkdir data/month
          python main.py

      - name: sshagent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          echo "The branched that was pushed is $branch"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "maps.media.mit.edu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFqXBJPFe+pH3L57o1ildAxHssG4lpkloTcw3Wbs64c7bL8M6hR0rre4ufpCKboVLn4trJqbKOPWtFgBJHsgqXA=" > ~/.ssh/known_hosts
          scp ./data/*.js root@maps.media.mit.edu:/root/map/data/
          scp ./data/year/*.js root@maps.media.mit.edu:/root/map/data/
          scp ./data/month/*.js root@maps.media.mit.edu:/root/map/data/
          scp ./web/*.js root@maps.media.mit.edu:/root/map/
          scp ./web/*.html root@maps.media.mit.edu:/root/map/

      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: data/*
